{% set name = "oommfpy" %}
{% set version = "1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fd338dd807097649b032ae3fb050f933bdbe5a04621be8fdfd2ae3083494e837

build:
  number: 1
  entry_points:
    - omf2vtk = oommfpy.tools.omf2vtk:omf2vtk_cli
    - plot_omf = oommfpy.tools.plot_slices:plot_omf_slices_cli
  script: "{{ PYTHON }} -m pip install . --no-deps --no-cache-dir --ignore-installed -vv :all: "

requirements:
  host:
    - click >=7.1,<8.0
    - cython >=0.29.23,<0.30.0
    - matplotlib >=3.3.4,<4.0.0
    - numpy >=1.20.3,<2.0.0
    - pip
    - python
    - scipy >=1.6.3,<2.0.0
    - poetry
  run:
    - click >=7.1,<8.0
    - cython >=0.29.23,<0.30.0
    - matplotlib >=3.3.4,<4.0.0
    - numpy >=1.20.3,<2.0.0
    - python
    - scipy >=1.6.3,<2.0.0
    - poetry

test:
  imports:
    - oommfpy
    - oommfpy.tools
  commands:
    - omf2vtk --help
    - plot_omf --help

about:
  home: https://github.com/davidcortesortuno/oommfpy
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Minimal Python lib to process OOMMF format output files
  doc_url: https://github.com/davidcortesortuno/oommfpy
  dev_url: https://github.com/davidcortesortuno/oommfpy

extra:
  recipe-maintainers:
    - https://github.com/gb119
